
-- hsql
CREATE TABLE book_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    create_time DATETIME,
    update_time DATETIME
)

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT,
    price INT NOT NULL,
    description VARCHAR(255),
    cover VARCHAR(255),
    create_time DATETIME,
    update_time DATETIME
);

-- 书种类准备数据
INSERT INTO book_category (name) VALUES ('Computer Science')

-- 首页
localhost:8080/book_category/all